### ISSUE TITLE
Issue with the setup

### ISSUE THREAD

**Issue by daemuu** [bboc/todoist-converter#1]
Hello bboc, 

As a kind of newbie into python stuff, i experience some difficulties to make this converter app working.

I am actually stuck a the first step of the setup process you mention in the Readme : 

I try to type `python setup.py` into the terminal but it does not work.
It returns me `python: can't open file 'setup.py': [Errno 2] No such file or directory`

I guess that is because the folder containing all the stuffs is still in my Download folder, but i don't know where to move it to make it works.

Would you have any further directions to give me please ?
Thanks a lot,

Damien

**Comment by bboc** [comment]
If you are on MacOS, you could try the Mac App at https://github.com/bboc/todoist-converter/releases/tag/v0.3

At the moment I don't have access to a development machine, so I can't test this. Will look into this and get back to you.

**Comment by bboc** [comment]
@atypicalchemist: I just found out the README is wrong, it should say `python setup.py install`. I tested this, and this command worked for me in a new virtual environment. 

Your issue, however appears to something else: Python does not find the file `setup.py`. You need to cd into the root directory of the project, i.e. the directory where setup.py is located. The project does not need to be in a specific directory.

Since you appear to be on a Mac, you might want to check out the Mac App, it has a very simple GUI and can be run without using the commandline, here's the link:  
 https://github.com/bboc/todoist-converter/releases/tag/v0.3

**Comment by daemuu** [comment]
@bboc: Thanks for your feedbacks !

Actually i downloaded and tried the Mac app, but it seems not to work as well : i uploaded a Todoist CSV file i had to convert it in OPML, but i never get output.

Maybe that is because for now i let the app in the download folder ? That sounds unlikely for me.

My current OS is Mac OS Sierra 10.12.6

**Comment by bboc** [comment]
@atypicalchemist I tested this, and can confirm the app does not convert to OPML. 

I am currently traveling, and will have access to my development machine again on Monday, then I will be able to investigate further.

I don't think the location of the app causes what is happening here, even though [Gatekeeper Path Randomization](https://mjtsai.com/blog/2016/06/16/gatekeeper-path-randomization/) might become another issue one the OPML problem is resolved. But I need to sort out the location of the output files in the app anyway, and I guess I will be able to address path randomisation at the same time.

**Comment by bboc** [comment]
@atypicalchemist I have created a new version of the app:
[tdconv-app-0.4rc1.zip](https://github.com/bboc/todoist-converter/files/2853282/tdconv-app-0.4rc1.zip)

I fixed two small issues which might be related to your problem, and I added error out put that would help explain what might go wrong. Can you try this version and send me the out put?

**Comment by daemuu** [comment]
Hi bboc,

I try the new app with the "basic-test.csv" which is in the test-data folder. The app was in the download folder, and the test file was in the desktop.

It didn't worked and i get the following :

![TC App snapshot](https://user-images.githubusercontent.com/30660422/52886796-cce4eb80-3175-11e9-91bb-de2fa817c118.png)

**Comment by bboc** [comment]
@atypicalchemist thanks, I see what's wrong now, I fixed the app 

[todoist-converter.v1.0rc1.zip](https://github.com/bboc/todoist-converter/files/2873410/todoist-converter.v1.0rc1.zip)

Can you confirm it's working for you now?

I also added some bells and whistles: You can now directly process the zip file downloaded from Todoist, or a full directory of csv or opml files

**Comment by daemuu** [comment]
Hey bboc,

Thanks a lot : it works perfectly well now : gratitude ! \°/ :)

I didn't tried yet to process the zip, but i don't know why it would not work !

Thanks again and have a good One,

Damien

**Comment by bboc** [comment]
@atypicalchemist glad that it works for you now. I'm closing this issue, let me know if anything else comes up.
